# -*- coding: utf-8 -*-
"""IMD days to OneBand.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKTi66Tm9OyhCpFPPNh4dRQgJs1adCwY
"""

import zipfile
import os

# Specify the path to your already uploaded ZIP file
zip_file = "/content/NCdaily_rainfall_geotiffs2025.zip"  # Replace with your file name if different

# Verify the file exists
if not os.path.exists(zip_file):
    print(f"Error: File {zip_file} does not exist.")
else:
    # Specify the extraction folder
    extract_path = '/content/extracted_files2025'
    os.makedirs(extract_path, exist_ok=True)  # Create the folder if it doesn't exist

    # Extract the ZIP file
    print(f"Extracting ZIP file: {zip_file} to {extract_path}...")
    try:
        with zipfile.ZipFile(zip_file, 'r') as zip_ref:
            zip_ref.extractall(extract_path)
        print(f"Extraction completed. Extracted files are in: {extract_path}")
    except zipfile.BadZipFile:
        print("Error: The file is not a valid ZIP file or is corrupted.")


print(f"Files extracted to {extract_path}")

pip install xarray netCDF4 rasterio numpy tqdm

import rasterio
import numpy as np
import glob

# Get all extracted TIFF files
tiff_files = sorted(glob.glob(os.path.join(extract_path, "*.tif")))

# Create a stack of all TIFFs
with rasterio.open(tiff_files[0]) as src:
    meta = src.meta.copy()
    meta.update(count=len(tiff_files))  # Update meta to reflect the number of bands

# Write the combined multi-band TIFF
combined_tiff_path = "/content/combined_rainfall2025.tif"
with rasterio.open(combined_tiff_path, 'w', **meta) as dst:
    for idx, tiff_file in enumerate(tiff_files, start=1):
        with rasterio.open(tiff_file) as src:
            dst.write_band(idx, src.read(1))  # Write each file as a band

print(f"Combined TIFF created at {combined_tiff_path}")