# -*- coding: utf-8 -*-
"""NetCDF to Daily GeoTIFF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wBmqSCRyZtiM5IGMFPwot2Fahk8IKYL
"""

pip install xarray netCDF4 rasterio numpy tqdm

#For NetCDF(.nc) files

import xarray as xr
import numpy as np
import rasterio
from rasterio.transform import from_origin
import os
import zipfile
from tqdm import tqdm

# Input and output file paths
input_nc_file = "/content/RF25_ind2025_rfp25.nc"
output_zip_file = "NCdaily_rainfall_geotiffs2025.zip"
output_folder = "/content/NCdaily_geotiffs2025"

# Create output directory
os.makedirs(output_folder, exist_ok=True)
# Open the NetCDF file
dataset = xr.open_dataset(input_nc_file)

# Extract required variables
rainfall_data = dataset['RAINFALL']  # Replace 'rainfall' with the actual variable name in your dataset
lon = dataset['LONGITUDE'].values  # Replace 'longitude' with the actual name in your dataset
lat = dataset['LATITUDE'].values  # Replace 'latitude' with the actual name in your dataset
days = rainfall_data.shape[0]

# Transform for GeoTIFF
transform = from_origin(lon[0] - 0.125, lat[-1] + 0.125, 0.25, 0.25)

# Save each day as GeoTIFF
print(f"Saving GeoTIFF files to {output_folder}...")
for day in tqdm(range(days), desc="Processing days"):
    day_data = rainfall_data[day, :, :].values
    day_data = np.flipud(day_data)  # Flip to match GeoTIFF orientation

    output_file = os.path.join(output_folder, f"day{day + 1}.tif")

    # Save the GeoTIFF
    with rasterio.open(
        output_file,
        'w',
        driver='GTiff',
        height=day_data.shape[0],
        width=day_data.shape[1],
        count=1,
        dtype=day_data.dtype,
        crs="EPSG:4326",
        transform=transform
    ) as dst:
        dst.write(day_data, 1)

# Compress GeoTIFF files into a ZIP archive
print(f"Compressing GeoTIFF files into {output_zip_file}...")
with zipfile.ZipFile(output_zip_file, 'w') as zipf:
    for root, _, files in os.walk(output_folder):
        for file in files:
            zipf.write(os.path.join(root, file), arcname=file)

# Cleanup
print(f"GeoTIFF files compressed into {output_zip_file}.")



#For Binary(.grd) files

import numpy as np
import rasterio
from rasterio.transform import from_origin
import os
import zipfile
from tqdm import tqdm

# Configuration
input_grd_file = "/content/Rainfall_ind2024_rfp25.grd"  # Change this to your .grd file path
output_zip_file = "GRDdaily_rainfall_geotiffs2024.zip"
output_folder = "/content/GRDdaily_geotiffs2024"

# Grid parameters (from IMD documentation)
GRID_SHAPE = (129, 135)  # (latitude, longitude)
RESOLUTION = 0.25        # degrees
LON_START = 66.5         # Eastern boundary of first grid cell
LAT_START = 6.5          # Southern boundary of first grid cell

# Create output directory
os.makedirs(output_folder, exist_ok=True)

# Calculate geotransform parameters
lat_max = LAT_START + (GRID_SHAPE[0] - 1) * RESOLUTION  # 38.5N
transform = from_origin(
    LON_START - RESOLUTION/2,  # Western edge of first cell
    lat_max + RESOLUTION/2,    # Northern edge of first cell
    RESOLUTION, RESOLUTION
)

# Calculate number of days from file size
bytes_per_day = GRID_SHAPE[0] * GRID_SHAPE[1] * 4  # 4 bytes per float32
file_size = os.path.getsize(input_grd_file)
days = file_size // bytes_per_day

# Process daily data
print(f"Converting {days} days from {input_grd_file}...")
with open(input_grd_file, "rb") as f:
    for day in tqdm(range(days), desc="Processing days"):
        # Read binary data for one day
        buffer = f.read(bytes_per_day)
        if not buffer:
            break

        # Convert to numpy array and reshape
        day_data = np.frombuffer(buffer, dtype=np.float32)
        day_data = day_data.reshape(GRID_SHAPE)

        # Flip data vertically (original: south->north, needed: north->south)
        day_data = np.flipud(day_data)

        # Write GeoTIFF
        output_file = os.path.join(output_folder, f"day{day+1}.tif")
        with rasterio.open(
            output_file,
            "w",
            driver="GTiff",
            height=GRID_SHAPE[0],
            width=GRID_SHAPE[1],
            count=1,
            dtype=day_data.dtype,
            crs="EPSG:4326",
            transform=transform,
            nodata=-999.0  # From IMD's documentation
        ) as dst:
            dst.write(day_data, 1)

# Compress results (same as your original code)
print(f"Compressing GeoTIFF files into {output_zip_file}...")
with zipfile.ZipFile(output_zip_file, "w") as zipf:
    for root, _, files in os.walk(output_folder):
        for file in files:
            zipf.write(os.path.join(root, file), arcname=file)

print(f"Conversion complete! GeoTIFFs archived in {output_zip_file}")



















#for 1st 4 months of 2025
#try1

import numpy as np
import rasterio
from rasterio.transform import from_origin
import os
import zipfile
from tqdm import tqdm

# Configuration
input_zip_file = "/content/daily data 2025.zip"  # Your input zip file
output_zip_file = "GRDdaily_geotiffs2025.zip"
output_folder = "/content/GRDdaily_geotiffs2025"
extracted_folder = "/content/extracted_GRDdaily_geotiffs2025"

# Grid parameters (from IMD documentation)
GRID_SHAPE = (129, 135)  # (latitude, longitude)
RESOLUTION = 0.25
LON_START = 66.5
LAT_START = 6.5

# Create directories
os.makedirs(output_folder, exist_ok=True)
os.makedirs(extracted_folder, exist_ok=True)

# Extract input zip
with zipfile.ZipFile(input_zip_file, 'r') as zip_ref:
    zip_ref.extractall(extracted_folder)

# Collect and sort files chronologically
all_files = []
for root, _, files in os.walk(extracted_folder):
    for file in files:
        if file.endswith('.grd') and file.startswith('rain_ind0.25_25'):
            all_files.append(os.path.join(root, file))

# Sort files by month and day using filename structure
all_files.sort(key=lambda x: (x.split('_')[4], x.split('_')[5]))  # Extracts MM and DD

# Geotransform setup
lat_max = LAT_START + (GRID_SHAPE[0] - 1) * RESOLUTION
transform = from_origin(
    LON_START - RESOLUTION/2,
    lat_max + RESOLUTION/2,
    RESOLUTION, RESOLUTION
)

# Process files in sorted order
print(f"Converting {len(all_files)} days...")
for day_idx, grd_file in enumerate(tqdm(all_files, desc="Processing"), start=1):
    with open(grd_file, 'rb') as f:
        day_data = np.frombuffer(f.read(), dtype=np.float32)
        day_data = day_data.reshape(GRID_SHAPE)
        day_data = np.flipud(day_data)

    output_file = os.path.join(output_folder, f"day{day_idx}.tif")
    with rasterio.open(
        output_file,
        'w',
        driver='GTiff',
        height=GRID_SHAPE[0],
        width=GRID_SHAPE[1],
        count=1,
        dtype=day_data.dtype,
        crs='EPSG:4326',
        transform=transform,
        nodata=-999.0
    ) as dst:
        dst.write(day_data, 1)

# Create final zip
print("Compressing results...")
with zipfile.ZipFile(output_zip_file, 'w') as zipf:
    for root, _, files in os.walk(output_folder):
        for file in files:
            zipf.write(os.path.join(root, file), arcname=file)

print(f"Conversion complete! Output: {output_zip_file}")

#for 1st 4 months of 2025
#try2

import numpy as np
import rasterio
from rasterio.transform import from_origin
import os
import zipfile
import re
from tqdm import tqdm
import tempfile
import shutil

# Configuration
input_zip_file = "/content/daily data 2025.zip"  # Change this to your input zip file
output_zip_file = "GRDdaily1_geotiffs2025.zip"
output_folder = "/content/GRDdaily1_geotiffs2025"

# Grid parameters (from IMD documentation)
GRID_SHAPE = (129, 135)  # (latitude, longitude)
RESOLUTION = 0.25        # degrees
LON_START = 66.5         # Eastern boundary of first grid cell
LAT_START = 6.5          # Southern boundary of first grid cell

# Create output directory
os.makedirs(output_folder, exist_ok=True)

# Calculate geotransform parameters
lat_max = LAT_START + (GRID_SHAPE[0] - 1) * RESOLUTION  # 38.5N
transform = from_origin(
    LON_START - RESOLUTION/2,  # Western edge of first cell
    lat_max + RESOLUTION/2,    # Northern edge of first cell
    RESOLUTION, RESOLUTION
)

# Create a temporary directory to extract the zip file
temp_dir = tempfile.mkdtemp()
print(f"Extracting {input_zip_file} to temporary directory...")

# Extract the zip file
with zipfile.ZipFile(input_zip_file, 'r') as zip_ref:
    zip_ref.extractall(temp_dir)

# Get all the .grd files and sort them by month and day
grd_files = []
for root, dirs, files in os.walk(temp_dir):
    for file in files:
        if file.endswith('.grd'):
            file_path = os.path.join(root, file)
            # Extract month and day from filename
            match = re.search(r'(\d{2})_(\d{2})\.grd$', file)
            if match:
                month, day = map(int, match.groups())
                grd_files.append((file_path, month, day))

# Sort files by month and day
grd_files.sort(key=lambda x: (x[1], x[2]))

print(f"Found {len(grd_files)} .grd files to process")

# Process each .grd file
day_counter = 1
for file_path, month, day in tqdm(grd_files, desc="Processing .grd files"):
    # Read the binary file
    with open(file_path, "rb") as f:
        buffer = f.read()

    # Check if we have the expected amount of data
    bytes_per_day = GRID_SHAPE[0] * GRID_SHAPE[1] * 4  # 4 bytes per float32
    if len(buffer) != bytes_per_day:
        print(f"Warning: Unexpected file size for {file_path}. Expected {bytes_per_day} bytes, got {len(buffer)} bytes.")
        continue

    # Convert to numpy array and reshape
    day_data = np.frombuffer(buffer, dtype=np.float32)
    day_data = day_data.reshape(GRID_SHAPE)

    # Flip data vertically (original: south->north, needed: north->south)
    day_data = np.flipud(day_data)

    # Write GeoTIFF
    output_file = os.path.join(output_folder, f"day{day_counter}.tif")
    with rasterio.open(
        output_file,
        "w",
        driver="GTiff",
        height=GRID_SHAPE[0],
        width=GRID_SHAPE[1],
        count=1,
        dtype=day_data.dtype,
        crs="EPSG:4326",
        transform=transform,
        nodata=-999.0  # From IMD's documentation
    ) as dst:
        dst.write(day_data, 1)

    day_counter += 1

# Clean up the temporary directory
shutil.rmtree(temp_dir)

# Compress results
print(f"Compressing GeoTIFF files into {output_zip_file}...")
with zipfile.ZipFile(output_zip_file, "w") as zipf:
    for root, _, files in os.walk(output_folder):
        for file in files:
            zipf.write(os.path.join(root, file), arcname=file)

print(f"Conversion complete! {day_counter-1} GeoTIFFs archived in {output_zip_file}")



















import numpy as np

with rasterio.open('/content/NCdaily_geotiffs2024/day1.tif') as src1, rasterio.open('/content/GRDdaily_geotiffs2024/day1.tif') as src2:
    arr1 = src1.read(1)
    arr2 = src2.read(1)

    print("Shapes equal?", arr1.shape == arr2.shape)
    print("Max difference:", np.max(np.abs(arr1 - arr2)))
    print("Are equal (within tolerance)?", np.allclose(arr1, arr2, atol=1e-20))

import numpy as np
import pandas as pd

# Load CSVs
df1 = pd.read_csv('/content/1111GRD2024ProcessedMeanRainfallGriddedData5000m.csv', header=None)
df2 = pd.read_csv('/content/1111NC2024ProcessedMeanRainfallGriddedData5000m.csv', header=None)

# Ensure both are numeric
df1 = df1.apply(pd.to_numeric, errors='coerce')
df2 = df2.apply(pd.to_numeric, errors='coerce')

# Check shape
if df1.shape != df2.shape:
    print("❌ Shape mismatch:", df1.shape, df2.shape)
else:
    # Element-wise comparison
    comparison = df1.values == df2.values
    all_match = np.all(comparison)

    if all_match:
        print("✅ All cells match exactly.")
    else:
        print("❌ Some cells differ.")
        # Optional: Show mismatched cells with positions and values
        mismatches = np.where(comparison == False)
        for row, col in zip(*mismatches):
            print(f"Mismatch at ({row}, {col}): CSV1={df1.iloc[row, col]}, CSV2={df2.iloc[row, col]}")

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSVs
csv1 = pd.read_csv("/content/1111NC2024ProcessedMeanRainfallGriddedData5000m.csv")
csv2 = pd.read_csv("/content/1111GRD2024ProcessedMeanRainfallGriddedData5000m.csv")

# Parse the relevant columns
# Assuming columns are labeled, not positional. If not, use `usecols=[1, 6]`
df1 = csv1[["Date", "Rainfall"]].copy()
df2 = csv2[["Date", "Rainfall"]].copy()

# Convert Date to datetime format
df1["Date"] = pd.to_datetime(df1["Date"], format='%d-%m-%Y')
df2["Date"] = pd.to_datetime(df2["Date"], format='%d-%m-%Y')

# Sort by date in case not already sorted
df1.sort_values("Date", inplace=True)
df2.sort_values("Date", inplace=True)

# Plot
plt.figure(figsize=(12, 6))
plt.plot(df1["Date"], df1["Rainfall"], label="From NetCDF", color="blue")
plt.plot(df2["Date"], df2["Rainfall"], label="From Binary", color="red", linestyle="dashed")

plt.title("Rainfall Comparison: NetCDF vs Binary")
plt.xlabel("Date")
plt.ylabel("Rainfall (mm)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()





start_date = pd.to_datetime('2024-03-01')
end_date = pd.to_datetime('2024-05-31')

df1_filtered = df1[(df1['Date'] >= start_date) & (df1['Date'] <= end_date)]
df2_filtered = df2[(df2['Date'] >= start_date) & (df2['Date'] <= end_date)]

# Plot the filtered data
plt.figure(figsize=(12, 6))
plt.plot(df1_filtered["Date"], df1_filtered["Rainfall"], label="From NetCDF", color="blue")
plt.plot(df2_filtered["Date"], df2_filtered["Rainfall"], label="From Binary", color="red", linestyle="dashed")

plt.title("Rainfall Comparison: NetCDF vs Binary (March-May 2024)")
plt.xlabel("Date")
plt.ylabel("Rainfall (mm)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

