# -*- coding: utf-8 -*-
"""copy of SoilMoisture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tY5IjgGJsIyQW7GBlWQ9TuBBjbDGo_Yq
"""

# !pip install -r requirements.txt

import numpy as np
import tensorflow as tf
import random
import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping
from tqdm.notebook import tqdm

# Set random seed for reproducibility
seed_value = 42
os.environ['PYTHONHASHSEED'] = str(seed_value)
random.seed(seed_value)
np.random.seed(seed_value)
tf.random.set_seed(seed_value)

# Function to load and combine soil moisture data
def load_soil_moisture_data():
    folder_path = '/content/soil_moisture_data'
    file_list = sorted([os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith('.csv')])
    dfs = []
    for filename in file_list:
        try:
            df = pd.read_csv(filename)
            # Check if 'system:index' column exists before trying to access it
            if 'system:index' in df.columns:
                df['Date'] = pd.to_datetime(df['Date'])
                df['Day_Number'] = df['system:index'].apply(lambda x: int(x.split('_')[0]))
                df['Grid_ID'] = df['system:index'].apply(lambda x: int(x.split('_')[1]))
                dfs.append(df)
            else:
                print(f"Skipping file '{filename}': 'system:index' column not found.")
        except Exception as e:
            print(f"Error processing file '{filename}': {e}")

    if len(dfs) == 0:
        print("No files were loaded successfully.")
        return pd.DataFrame() # Return an empty DataFrame if no files loaded

    combined_df = pd.concat(dfs, ignore_index=True)
    combined_df = combined_df.sort_values(['Grid_ID', 'Date'])
    return combined_df

# Create sequences for LSTM
def create_sequences(data, n_steps_in=13, n_steps_out=1):
    X, y = [], []
    for i in range(len(data) - n_steps_in - n_steps_out + 1):
        X.append(data[i:i+n_steps_in])
        y.append(data[i+n_steps_in:i+n_steps_in+n_steps_out])
    return np.array(X), np.array(y)

# Function to build and train LSTM model for a grid
def train_lstm_model(grid_id, soil_moisture_data):
    grid_cell_data = soil_moisture_data[soil_moisture_data['Grid_ID'] == grid_id]
    ts_data = grid_cell_data[['Date', 'Rootzone_Soil_Moisture']].copy()
    ts_data.set_index('Date', inplace=True)
    monthly_data = ts_data.resample('M').mean()
    monthly_data['month'] = monthly_data.index.month
    train_data = monthly_data
    scaler_sm = MinMaxScaler(feature_range=(0, 1))
    scaler_month = MinMaxScaler(feature_range=(0, 1))
    train_sm_scaled = scaler_sm.fit_transform(train_data[['Rootzone_Soil_Moisture']])
    train_month_scaled = scaler_month.fit_transform(train_data[['month']])
    train_scaled = np.hstack((train_sm_scaled, train_month_scaled))
    n_steps_in = 13
    n_steps_out = 1
    if len(train_scaled) <= n_steps_in:
        print(f"Not enough training data for Grid {grid_id}")
        return None
    X_train, y_train = create_sequences(train_scaled, n_steps_in, n_steps_out)
    y_train = y_train[:, 0, 0].reshape(-1, 1)
    input_shape = (n_steps_in, train_scaled.shape[1])
    model = Sequential()
    model.add(Bidirectional(LSTM(64, activation='relu', return_sequences=True), input_shape=input_shape))
    model.add(Dropout(0.2))
    model.add(LSTM(32, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(1))
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.005)
    model.compile(optimizer=optimizer, loss='mse')
    early_stopping = EarlyStopping(
        monitor='val_loss',
        patience=15,
        restore_best_weights=True
    )
    model.fit(
        X_train, y_train,
        epochs=50,
        batch_size=32,
        validation_split=0.2,
        callbacks=[early_stopping],
        verbose=0
    )
    return {
        'model': model,
        'scaler_sm': scaler_sm,
        'scaler_month': scaler_month,
        'last_sequence': train_scaled[-n_steps_in:],
        'last_date': monthly_data.index[-1]
    }

# Function to forecast future soil moisture
def forecast_lstm(model_info, forecast_steps=12):
    model = model_info['model']
    scaler_sm = model_info['scaler_sm']
    scaler_month = model_info['scaler_month']
    input_seq = model_info['last_sequence']
    last_date = model_info['last_date']
    forecast_index = pd.date_range(
        start=last_date + pd.DateOffset(months=1),
        periods=forecast_steps,
        freq='M'
    )
    forecast_months = np.array([date.month for date in forecast_index]).reshape(-1, 1)
    forecast_months_scaled = scaler_month.transform(forecast_months)
    forecasts = []
    curr_seq = input_seq.copy()
    for i in range(forecast_steps):
        x_input = curr_seq.reshape(1, curr_seq.shape[0], curr_seq.shape[1])
        yhat = model.predict(x_input, verbose=0)
        forecasts.append(yhat[0, 0])
        curr_seq = np.vstack((curr_seq[1:], np.array([[yhat[0, 0], forecast_months_scaled[i, 0]]])))
    forecasts = np.array(forecasts).reshape(-1, 1)
    forecasts = scaler_sm.inverse_transform(forecasts)
    return {
        'forecast_index': forecast_index,
        'forecasts': forecasts.flatten()
    }

# Function to evaluate LSTM prediction accuracy for 2024
def evaluate_lstm_accuracy(grid_id, soil_moisture_data):
    grid_cell_data = soil_moisture_data[soil_moisture_data['Grid_ID'] == grid_id]
    ts_data = grid_cell_data[['Date', 'Rootzone_Soil_Moisture']].copy()
    ts_data.set_index('Date', inplace=True)
    monthly_data = ts_data.resample('M').mean()
    monthly_data['month'] = monthly_data.index.month
    train_data = monthly_data[monthly_data.index.year < 2024]
    test_data = monthly_data[monthly_data.index.year == 2024]
    if len(test_data) < 2:
        print(f"Insufficient 2024 data available for Grid {grid_id}")
        return None
    scaler_sm = MinMaxScaler(feature_range=(0, 1))
    scaler_month = MinMaxScaler(feature_range=(0, 1))
    train_sm_scaled = scaler_sm.fit_transform(train_data[['Rootzone_Soil_Moisture']])
    train_month_scaled = scaler_month.fit_transform(train_data[['month']])
    train_scaled = np.hstack((train_sm_scaled, train_month_scaled))
    n_steps_in = 13
    n_steps_out = 1
    if len(train_scaled) <= n_steps_in:
        print(f"Not enough training data for Grid {grid_id}")
        return None
    X_train, y_train = create_sequences(train_scaled, n_steps_in, n_steps_out)
    y_train = y_train[:, 0, 0].reshape(-1, 1)
    input_shape = (n_steps_in, train_scaled.shape[1])
    model = Sequential()
    model.add(Bidirectional(LSTM(64, activation='relu', return_sequences=True), input_shape=input_shape))
    model.add(Dropout(0.2))
    model.add(LSTM(32, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(1))
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.005)
    model.compile(optimizer=optimizer, loss='mse')
    early_stopping = EarlyStopping(
        monitor='val_loss',
        patience=15,
        restore_best_weights=True
    )
    model.fit(
        X_train, y_train,
        epochs=50,
        batch_size=32,
        validation_split=0.2,
        callbacks=[early_stopping],
        verbose=0
    )
    # Prepare test data
    test_sm_scaled = scaler_sm.transform(test_data[['Rootzone_Soil_Moisture']])
    test_month_scaled = scaler_month.transform(test_data[['month']])
    test_scaled = np.hstack((test_sm_scaled, test_month_scaled))
    input_data = np.vstack((train_scaled[-n_steps_in:], test_scaled))
    test_predictions = []
    for i in range(len(test_data)):
        x_input = input_data[i:i+n_steps_in]
        x_input = x_input.reshape(1, n_steps_in, train_scaled.shape[1])
        yhat = model.predict(x_input, verbose=0)
        test_predictions.append(yhat[0, 0])
        if i+n_steps_in < len(input_data) and i < len(test_data)-1:
            input_data[i+n_steps_in, 0] = test_scaled[i+1, 0]
    test_predictions = np.array(test_predictions).reshape(-1, 1)
    test_pred_sm = scaler_sm.inverse_transform(test_predictions)
    mse = mean_squared_error(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm)
    r2 = r2_score(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm)
    correlation = np.corrcoef(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm.flatten())[0, 1]
    mape = np.mean(np.abs((test_data['Rootzone_Soil_Moisture'].values - test_pred_sm.flatten()) /
                          (test_data['Rootzone_Soil_Moisture'].values + 0.01))) * 100
    plt.figure(figsize=(12, 6))
    plt.plot(test_data.index, test_data['Rootzone_Soil_Moisture'], label='Actual 2024 Soil Moisture')
    plt.plot(test_data.index, test_pred_sm, color='red', label='LSTM Forecast')
    plt.title(f'LSTM Forecast Accuracy for Grid {grid_id} (2024)', fontsize=24)
    plt.xlabel('Date', fontsize=21)
    plt.ylabel('Soil Moisture', fontsize=21)
    plt.legend(fontsize=18)
    plt.tick_params(axis='both', which='major', labelsize=15)
    plt.grid(True)
    plt.savefig(f'lstm_soilmoisture_accuracy_grid_{grid_id}.png')
    plt.show()
    comparison_df = pd.DataFrame({
        'Month': test_data.index.strftime('%Y-%m'),
        'Actual Soil Moisture': test_data['Rootzone_Soil_Moisture'].values.round(3),
        'Predicted Soil Moisture': test_pred_sm.flatten().round(3),
        'Difference': (test_data['Rootzone_Soil_Moisture'].values - test_pred_sm.flatten()).round(3)
    })
    print(f"\nActual vs Predicted Soil Moisture for Grid {grid_id} (2024):")
    print(comparison_df)
    return {
        'grid_id': grid_id,
        'rmse': rmse,
        'mae': mae,
        'mape': mape,
        'r2': r2,
        'correlation': correlation,
        'actual_values': test_data['Rootzone_Soil_Moisture'].values,
        'predicted_values': test_pred_sm.flatten()
    }

# Load all soil moisture data
print("Loading soil moisture data...")
soil_moisture_data = load_soil_moisture_data()
unique_grid_ids = sorted(soil_moisture_data['Grid_ID'].unique())
grid_sets = [unique_grid_ids[i:i+9] for i in range(0, 81, 9)]
grid_sets.append(unique_grid_ids[81:])

print(f"Created {len(grid_sets)} sets of grids")
for i, grid_set in enumerate(grid_sets):
    print(f"Set {i+1}: {len(grid_set)} grids - {grid_set}")

# Process each set of grids for forecasting
for set_idx, grid_set in enumerate(grid_sets):
    print(f"\nProcessing Set {set_idx+1} with {len(grid_set)} grids for forecasting")
    forecasts_list = []
    for grid_id in tqdm(grid_set):
        model_info = train_lstm_model(grid_id, soil_moisture_data)
        if model_info is not None:
            forecast_result = forecast_lstm(model_info)
            forecast_result['grid_id'] = grid_id
            forecasts_list.append(forecast_result)
    if not forecasts_list:
        print(f"No valid forecasts for Set {set_idx+1}")
        continue
    plt.figure(figsize=(15, 8))
    for result in forecasts_list:
        grid_id = result['grid_id']
        plt.plot(result['forecast_index'],
                 result['forecasts'],
                 label=f'Grid {grid_id}')
    plt.xlabel('Date', fontsize=21)
    plt.ylabel('Forecasted Soil Moisture', fontsize=21)
    plt.title(f'LSTM Soil Moisture Forecast for Grid Set {set_idx+1}', fontsize=24)
    plt.legend(loc='upper left', fontsize=18, ncol=3)
    plt.tick_params(axis='both', which='major', labelsize=15)
    plt.grid(True)
    plt.savefig(f'lstm_soilmoisture_forecast_set_{set_idx+1}.png', dpi=300)
    plt.show()
    forecast_df = pd.DataFrame()
    # Use pandas.concat instead of _append for better performance
    temp_dfs = []
    for result in forecasts_list:
        grid_id = result['grid_id']
        temp_df = pd.DataFrame({
            'Date': result['forecast_index'],
            'Grid_ID': grid_id,
            'Forecasted_Soil_Moisture': result['forecasts']
        })
        temp_dfs.append(temp_df)
    if temp_dfs:
         forecast_df = pd.concat(temp_dfs, ignore_index=True)
    forecast_df.to_csv(f'lstm_soilmoisture_forecast_results_set_{set_idx+1}.csv', index=False)
    print(f"Saved forecast results for Set {set_idx+1} to 'lstm_soilmoisture_forecast_results_set_{set_idx+1}.csv'")

# Validate the model using 2024 data
print("\nValidating LSTM model using 2024 data")
validation_grids = []
for grid_set in grid_sets:
    # Take the first 3 grids from each set for validation
    validation_grids.extend(grid_set[:3])
accuracy_results = []
for grid_id in tqdm(validation_grids):
    result = evaluate_lstm_accuracy(grid_id, soil_moisture_data)
    if result:
        accuracy_results.append(result)
        print(f"\nAccuracy Metrics for Grid {grid_id}:")
        print(f"RMSE: {result['rmse']:.3f}")
        print(f"MAE: {result['mae']:.3f}")
        print(f"MAPE: {result['mape']:.2f}%")
        print(f"R²: {result['r2']:.4f}")
        print(f"Correlation: {result['correlation']:.4f}")
if accuracy_results:
    summary_df = pd.DataFrame([
        {
            'Grid_ID': result['grid_id'],
            'RMSE': result['rmse'],
            'MAE': result['mae'],
            'MAPE': result['mape'],
            'R²': result['r2'],
            'Correlation': result['correlation']
        }
        for result in accuracy_results
    ])
    print("\nSummary of LSTM Prediction Accuracy:")
    print(summary_df)
    summary_df.to_csv('lstm_soilmoisture_accuracy_summary.csv', index=False)
    print("Saved accuracy summary to 'lstm_soilmoisture_accuracy_summary.csv'")

# !pip install -r requirements.txt
# requirements.txt should now include: torch, numpy, pandas, matplotlib, scikit-learn, tqdm

import numpy as np
import torch
import torch.nn as nn
import random
import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from tqdm.notebook import tqdm
import copy

# ==============================================================================
#  PYTORCH SETUP AND REPRODUCIBILITY
# ==============================================================================
# Set random seed for reproducibility
seed_value = 42
os.environ['PYTHONHASHSEED'] = str(seed_value)
random.seed(seed_value)
np.random.seed(seed_value)
torch.manual_seed(seed_value)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed_value)
    # The following two lines are needed for full reproducibility on GPU
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Check for GPU and set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# ==============================================================================
#  PYTORCH MODEL DEFINITION
# ==============================================================================
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2, output_size, dropout_rate):
        super(LSTMModel, self).__init__()
        # PyTorch LSTM uses tanh/sigmoid activations internally, which is standard.
        self.lstm1 = nn.LSTM(input_size, hidden_size1, batch_first=True, bidirectional=True)
        self.dropout1 = nn.Dropout(dropout_rate)
        # Input to the second LSTM is hidden_size1 * 2 because the first is bidirectional.
        self.lstm2 = nn.LSTM(hidden_size1 * 2, hidden_size2, batch_first=True)
        self.dropout2 = nn.Dropout(dropout_rate)
        self.fc = nn.Linear(hidden_size2, output_size)

    def forward(self, x):
        out, _ = self.lstm1(x)
        out = self.dropout1(out)
        out, _ = self.lstm2(out)
        # We only need the output from the last time step for the final prediction.
        out = out[:, -1, :]
        out = self.dropout2(out)
        out = self.fc(out)
        return out

# Function to load and combine soil moisture data (UNCHANGED)
def load_soil_moisture_data():
    folder_path = '/content/soil_moisture_data'
    if not os.path.exists(folder_path):
        print(f"Error: Directory not found at '{folder_path}'")
        return pd.DataFrame()

    file_list = sorted([os.path.join(folder_path, f) for f in os.listdir(folder_path) if f.endswith('.csv')])
    dfs = []
    for filename in file_list:
        try:
            df = pd.read_csv(filename)
            if 'system:index' in df.columns:
                df['Date'] = pd.to_datetime(df['Date'])
                df['Day_Number'] = df['system:index'].apply(lambda x: int(x.split('_')[0]))
                df['Grid_ID'] = df['system:index'].apply(lambda x: int(x.split('_')[1]))
                dfs.append(df)
            else:
                print(f"Skipping file '{filename}': 'system:index' column not found.")
        except Exception as e:
            print(f"Error processing file '{filename}': {e}")
    if not dfs:
        print("No files were loaded successfully.")
        return pd.DataFrame()
    combined_df = pd.concat(dfs, ignore_index=True)
    combined_df = combined_df.sort_values(['Grid_ID', 'Date'])
    return combined_df

# Create sequences for LSTM (UNCHANGED)
def create_sequences(data, n_steps_in=13, n_steps_out=1):
    X, y = [], []
    for i in range(len(data) - n_steps_in - n_steps_out + 1):
        X.append(data[i:i+n_steps_in])
        y.append(data[i+n_steps_in:i+n_steps_in+n_steps_out])
    return np.array(X), np.array(y)

# Function to build and train PyTorch LSTM model for a grid
def train_pytorch_model(grid_id, soil_moisture_data, n_steps_in=13):
    grid_cell_data = soil_moisture_data[soil_moisture_data['Grid_ID'] == grid_id]
    ts_data = grid_cell_data[['Date', 'Rootzone_Soil_Moisture']].copy().set_index('Date')
    monthly_data = ts_data.resample('M').mean()
    monthly_data['month'] = monthly_data.index.month

    scaler_sm = MinMaxScaler(feature_range=(0, 1))
    scaler_month = MinMaxScaler(feature_range=(0, 1))
    train_sm_scaled = scaler_sm.fit_transform(monthly_data[['Rootzone_Soil_Moisture']])
    train_month_scaled = scaler_month.fit_transform(monthly_data[['month']])
    train_scaled = np.hstack((train_sm_scaled, train_month_scaled))

    if len(train_scaled) <= n_steps_in:
        print(f"Not enough training data for Grid {grid_id}")
        return None

    X, y = create_sequences(train_scaled, n_steps_in, 1)
    y = y[:, 0, 0].reshape(-1, 1)

    split_idx = int(len(X) * 0.8)
    X_train, X_val, y_train, y_val = X[:split_idx], X[split_idx:], y[:split_idx], y[split_idx:]

    X_train_tensor = torch.from_numpy(X_train).float().to(device)
    y_train_tensor = torch.from_numpy(y_train).float().to(device)
    X_val_tensor = torch.from_numpy(X_val).float().to(device)
    y_val_tensor = torch.from_numpy(y_val).float().to(device)

    model = LSTMModel(input_size=train_scaled.shape[1], hidden_size1=64, hidden_size2=32, output_size=1, dropout_rate=0.2).to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.005)

    patience, best_val_loss, epochs_no_improve, best_model_weights = 15, float('inf'), 0, None

    for epoch in range(50):
        model.train()
        optimizer.zero_grad()
        outputs = model(X_train_tensor)
        loss = criterion(outputs, y_train_tensor)
        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            val_outputs = model(X_val_tensor)
            val_loss = criterion(val_outputs, y_val_tensor).item()

        if val_loss < best_val_loss:
            best_val_loss, epochs_no_improve, best_model_weights = val_loss, 0, copy.deepcopy(model.state_dict())
        else:
            epochs_no_improve += 1
        if epochs_no_improve >= patience:
            break

    if best_model_weights:
        model.load_state_dict(best_model_weights)

    return {
        'model': model,
        'scaler_sm': scaler_sm,
        'scaler_month': scaler_month,
        'last_sequence': train_scaled[-n_steps_in:],
        'last_date': monthly_data.index[-1],
        'monthly_data': monthly_data
    }

# Function to forecast future soil moisture with PyTorch model
def forecast_pytorch(model_info, forecast_steps=12):
    model = model_info['model']
    scaler_sm = model_info['scaler_sm']
    scaler_month = model_info['scaler_month']
    input_seq_np = model_info['last_sequence']
    last_date = model_info['last_date']

    forecast_index = pd.date_range(start=last_date + pd.DateOffset(months=1), periods=forecast_steps, freq='M')
    forecast_months = np.array([date.month for date in forecast_index]).reshape(-1, 1)
    forecast_months_scaled = scaler_month.transform(forecast_months)

    forecasts = []
    curr_seq_np = input_seq_np.copy()

    model.eval()
    with torch.no_grad():
        for i in range(forecast_steps):
            x_input = torch.from_numpy(curr_seq_np).float().unsqueeze(0).to(device)
            yhat_tensor = model(x_input)
            yhat = yhat_tensor.cpu().item()
            forecasts.append(yhat)
            new_row = np.array([[yhat, forecast_months_scaled[i, 0]]])
            curr_seq_np = np.vstack((curr_seq_np[1:], new_row))

    forecasts = np.array(forecasts).reshape(-1, 1)
    forecasts = scaler_sm.inverse_transform(forecasts)

    return {
        'forecast_index': forecast_index,
        'forecasts': forecasts.flatten()
    }

# Function to retrain on extended data and forecast the next year (2026)
def retrain_and_forecast_next_year_pytorch(original_monthly_data, forecast_2025_result, forecast_steps=12, n_steps_in=13):
    forecast_df_2025 = pd.DataFrame({
        'Date': forecast_2025_result['forecast_index'],
        'Rootzone_Soil_Moisture': forecast_2025_result['forecasts']
    }).set_index('Date')

    extended_data = pd.concat([original_monthly_data, forecast_df_2025])
    extended_data['month'] = extended_data.index.month

    # This function trains a model on the extended data and then forecasts
    scaler_sm = MinMaxScaler(feature_range=(0, 1))
    scaler_month = MinMaxScaler(feature_range=(0, 1))
    sm_scaled = scaler_sm.fit_transform(extended_data[['Rootzone_Soil_Moisture']])
    month_scaled = scaler_month.fit_transform(extended_data[['month']])
    train_scaled = np.hstack((sm_scaled, month_scaled))

    if len(train_scaled) <= n_steps_in: return None

    X, y = create_sequences(train_scaled, n_steps_in, 1)
    y = y[:, 0, 0].reshape(-1, 1)
    split_idx = int(len(X) * 0.8)
    X_train, X_val, y_train, y_val = X[:split_idx], X[split_idx:], y[:split_idx], y[split_idx:]
    X_train_tensor, y_train_tensor = torch.from_numpy(X_train).float().to(device), torch.from_numpy(y_train).float().to(device)
    X_val_tensor, y_val_tensor = torch.from_numpy(X_val).float().to(device), torch.from_numpy(y_val).float().to(device)

    model = LSTMModel(input_size=train_scaled.shape[1], hidden_size1=64, hidden_size2=32, output_size=1, dropout_rate=0.2).to(device)
    criterion, optimizer = nn.MSELoss(), torch.optim.Adam(model.parameters(), lr=0.005)

    patience, best_val_loss, epochs_no_improve, best_model_weights = 15, float('inf'), 0, None
    for epoch in range(50):
        model.train(); optimizer.zero_grad(); outputs = model(X_train_tensor); loss = criterion(outputs, y_train_tensor); loss.backward(); optimizer.step()
        model.eval()
        with torch.no_grad(): val_loss = criterion(model(X_val_tensor), y_val_tensor).item()
        if val_loss < best_val_loss: best_val_loss, epochs_no_improve, best_model_weights = val_loss, 0, copy.deepcopy(model.state_dict())
        else: epochs_no_improve += 1
        if epochs_no_improve >= patience: break
    if best_model_weights: model.load_state_dict(best_model_weights)

    model_info = {
        'model': model,
        'scaler_sm': scaler_sm,
        'scaler_month': scaler_month,
        'last_sequence': train_scaled[-n_steps_in:],
        'last_date': extended_data.index[-1]
    }
    return forecast_pytorch(model_info, forecast_steps=forecast_steps)

# ==============================================================================
# CORRECTED EVALUATION FUNCTION
# ==============================================================================
def evaluate_pytorch_accuracy_original_method(grid_id, soil_moisture_data, n_steps_in=13):
    """
    This function replicates the ORIGINAL one-step-ahead prediction method for validation.
    It trains a model on data before 2024 and then makes predictions for each month
    of 2024 using the actual preceding data, which should result in higher accuracy scores.
    """
    grid_cell_data = soil_moisture_data[soil_moisture_data['Grid_ID'] == grid_id]
    ts_data = grid_cell_data[['Date', 'Rootzone_Soil_Moisture']].set_index('Date')
    monthly_data = ts_data.resample('M').mean()
    monthly_data['month'] = monthly_data.index.month

    train_data = monthly_data[monthly_data.index.year < 2024]
    test_data = monthly_data[monthly_data.index.year == 2024]
    if len(test_data) < 2: return None

    # --- Step 1: Train the model on pre-2024 data ---
    model_info = train_pytorch_model(grid_id, train_data)
    if not model_info: return None

    model = model_info['model']
    scaler_sm = model_info['scaler_sm']
    scaler_month = model_info['scaler_month']

    # --- Step 2: Prepare the full dataset for one-step-ahead prediction ---
    full_scaled_data = model_info['last_sequence'] # Last 13 months of training data

    test_sm_scaled = scaler_sm.transform(test_data[['Rootzone_Soil_Moisture']])
    test_month_scaled = scaler_month.transform(test_data[['month']])
    test_scaled = np.hstack((test_sm_scaled, test_month_scaled))

    # Combine last part of training data with actual test data
    input_data_np = np.vstack((full_scaled_data, test_scaled))

    # --- Step 3: Perform one-step-ahead predictions ---
    test_predictions = []
    model.eval()
    with torch.no_grad():
        for i in range(len(test_data)):
            # The input sequence is always from ground-truth data
            x_input_np = input_data_np[i : i + n_steps_in]
            x_input = torch.from_numpy(x_input_np).float().unsqueeze(0).to(device)
            yhat = model(x_input).cpu().item()
            test_predictions.append(yhat)

    test_pred_sm = scaler_sm.inverse_transform(np.array(test_predictions).reshape(-1, 1))

    # --- Step 4: Calculate metrics and plot ---
    rmse = np.sqrt(mean_squared_error(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm))
    mae = mean_absolute_error(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm)
    r2 = r2_score(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm)
    correlation = np.corrcoef(test_data['Rootzone_Soil_Moisture'].values, test_pred_sm.flatten())[0, 1]
    mape = np.mean(np.abs((test_data['Rootzone_Soil_Moisture'].values - test_pred_sm.flatten()) / (test_data['Rootzone_Soil_Moisture'].values + 1e-6))) * 100

    plt.figure(figsize=(12, 6))
    plt.plot(test_data.index, test_data['Rootzone_Soil_Moisture'], label='Actual 2024 Soil Moisture')
    plt.plot(test_data.index, test_pred_sm, color='red', label='PyTorch LSTM Forecast (One-Step)')
    plt.title(f'PyTorch LSTM Forecast Accuracy for Grid {grid_id} (2024)', fontsize=24)
    plt.xlabel('Date', fontsize=21); plt.ylabel('Soil Moisture', fontsize=21); plt.legend(fontsize=18)
    plt.tick_params(axis='both', which='major', labelsize=15); plt.grid(True)
    plt.savefig(f'pytorch_lstm_soilmoisture_accuracy_grid_{grid_id}.png'); plt.show()

    comparison_df = pd.DataFrame({'Month': test_data.index.strftime('%Y-%m'), 'Actual': test_data['Rootzone_Soil_Moisture'].values.round(3), 'Predicted': test_pred_sm.flatten().round(3)})
    print(f"\nActual vs Predicted Soil Moisture for Grid {grid_id} (2024):\n{comparison_df}")

    return {'grid_id': grid_id, 'rmse': rmse, 'mae': mae, 'mape': mape, 'r2': r2, 'correlation': correlation}


# ==============================================================================
# MAIN SCRIPT EXECUTION
# ==============================================================================
soil_moisture_data = load_soil_moisture_data()

if not soil_moisture_data.empty:
    unique_grid_ids = sorted(soil_moisture_data['Grid_ID'].unique())
    grid_sets = [unique_grid_ids[i:i + 9] for i in range(0, len(unique_grid_ids), 9)]
    print(f"\nCreated {len(grid_sets)} sets of grids")

    for set_idx, grid_set in enumerate(grid_sets):
        print(f"\nProcessing Set {set_idx+1} for 2025 & 2026 soil moisture forecasting using PyTorch")
        forecasts_list_2025, forecasts_list_2026 = [], []

        for grid_id in tqdm(grid_set, desc=f"Forecasting for Set {set_idx+1}"):
            model_info_2025 = train_pytorch_model(grid_id, soil_moisture_data)
            if model_info_2025:
                forecast_result_2025 = forecast_pytorch(model_info_2025)
                forecast_result_2025['grid_id'] = grid_id
                forecasts_list_2025.append(forecast_result_2025)

                forecast_result_2026 = retrain_and_forecast_next_year_pytorch(model_info_2025['monthly_data'], forecast_result_2025)
                if forecast_result_2026:
                    forecast_result_2026['grid_id'] = grid_id
                    forecasts_list_2026.append(forecast_result_2026)

        if not forecasts_list_2025: continue

        plt.figure(figsize=(15, 8)); colors = plt.cm.viridis(np.linspace(0, 1, len(forecasts_list_2025)))
        for i, res2025 in enumerate(forecasts_list_2025):
            grid_id, color = res2025['grid_id'], colors[i]
            plt.plot(res2025['forecast_index'], res2025['forecasts'], label=f'Grid {grid_id}', color=color, linestyle='-')
            for res2026 in forecasts_list_2026:
                if res2026['grid_id'] == grid_id: plt.plot(res2026['forecast_index'], res2026['forecasts'], color=color, linestyle='--'); break

        plt.xlabel('Date', fontsize=21); plt.ylabel('Forecasted Soil Moisture', fontsize=21)
        plt.title(f'PyTorch LSTM Soil Moisture Forecast for 2025 & 2026 (Set {set_idx+1})', fontsize=24)
        from matplotlib.lines import Line2D
        custom_lines = [Line2D([0], [0], color='black', lw=2), Line2D([0], [0], color='black', lw=2, linestyle='--')]
        plt.legend(handles=custom_lines, labels=['2025 Forecast', '2026 Forecast'], loc='upper left', fontsize=18)
        plt.tick_params(axis='both', which='major', labelsize=15); plt.grid(True)
        plt.savefig(f'pytorch_lstm_soilmoisture_forecast_2025_2026_set_{set_idx+1}.png', dpi=300); plt.show()

        temp_dfs = []
        for result in forecasts_list_2025 + forecasts_list_2026:
            temp_dfs.append(pd.DataFrame({'Date': result['forecast_index'], 'Grid_ID': result['grid_id'], 'Forecasted_Soil_Moisture': result['forecasts']}))
        if temp_dfs:
            forecast_df = pd.concat(temp_dfs, ignore_index=True).sort_values(['Grid_ID', 'Date'])
            csv_filename = f'pytorch_lstm_soilmoisture_forecast_2025_2026_set_{set_idx+1}.csv'
            forecast_df.to_csv(csv_filename, index=False)
            print(f"Saved forecast results for Set {set_idx+1} to '{csv_filename}'")

    print("\n" + "="*80); print("VALIDATING PYTORCH LSTM MODEL USING 2024 DATA (ORIGINAL METHOD)"); print("="*80)
    validation_grids = [grid for grid_set in grid_sets for grid in grid_set[:3]]
    # Call the corrected evaluation function
    accuracy_results = [result for grid_id in tqdm(validation_grids, desc="Validating Models") if (result := evaluate_pytorch_accuracy_original_method(grid_id, soil_moisture_data))]

    if accuracy_results:
        summary_df = pd.DataFrame(accuracy_results)
        print("\n" + "="*80); print("SUMMARY OF PYTORCH LSTM PREDICTION ACCURACY:"); print("="*80); print(summary_df.round(4).to_string(index=False))
        print("\nOverall Statistics:"); print(f"Average RMSE: {summary_df['rmse'].mean():.4f}"); print(f"Average R²: {summary_df['r2'].mean():.4f}")
        summary_df.to_csv('pytorch_lstm_soilmoisture_accuracy_summary.csv', index=False)
        print(f"\nSaved accuracy summary to 'pytorch_lstm_soilmoisture_accuracy_summary.csv'")

    print("\n" + "="*80); print("PYTORCH SOIL MOISTURE FORECASTING AND VALIDATION COMPLETED!"); print("="*80)